"""empty message

Revision ID: 0a667ce3ac49
Revises: 5a8c36bece0f
Create Date: 2024-02-22 16:01:32.140611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a667ce3ac49'
down_revision = '5a8c36bece0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('continue_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinate', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('continue_name')

    # ### end Alembic commands ###
