"""empty message

Revision ID: 9011127fa1a8
Revises: c3b8873c6772
Create Date: 2024-02-23 19:11:11.931979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9011127fa1a8'
down_revision = 'c3b8873c6772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('continue_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coordinate', schema=None) as batch_op:
        batch_op.drop_column('continue_path')

    # ### end Alembic commands ###
