"""empty message

Revision ID: daf49544571c
Revises: 94a58a91ad59
Create Date: 2024-02-23 14:26:17.454002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf49544571c'
down_revision = '94a58a91ad59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_closet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_closet', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
